#!/usr/bin/env python

import sys, os, re

class Transformer:
    def __init__(self):
        self.context = None

    def transform(self, only, l):
        regex = "^\S+\s+\S+\s+\S+\s+\S+\s+(\S+)\[\d+\]\s+<(.*)>: (.*)$"

        m = re.match(regex, l)

        if m:
            self.context = m.group(1)
            msg = m.group(3)

            if self.context == only:
                return msg
        else:
            if self.context == only or self.context is None:
                return re.sub("^\t","",l)

        return None

def main():
    assert len(sys.argv) == 2, "You need to pass the app identifier as sole argument"

    transformer = Transformer()

    while True:
        line = sys.stdin.readline().rstrip()
        if not line:
            break

        result = transformer.transform(sys.argv[1], line)

        if result:
            sys.stdout.write(result + "\n")
            sys.stdout.flush()

try:
    main()
except KeyboardInterrupt:
    sys.exit(0)
